# Generated by Django 4.2.2 on 2023-06-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('analyzed', models.BooleanField(default=False, verbose_name='Analisado?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.customer', verbose_name='Cliente')),
            ],
        ),
    ]
